<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-07-16 15:47

$extensionPath = t3lib_extMgm::extPath('seminarsyac');
return array(
	'tx_seminarsyac_eventsprovider' => $extensionPath . 'class.tx_seminarsyac_EventsProvider.php',
);
?>