<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-07-16 15:36

$extensionPath = t3lib_extMgm::extPath('seminarsyac');
return array(
);
?>